# Generated by Django 5.2 on 2025-06-01 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the product name (max 255 characters).', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Title.', max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, help_text='Optional content or description.', null=True, verbose_name='Content')),
                ('poster', models.FileField(blank=True, help_text='Upload an image', null=True, upload_to='products/posters/%Y/%d/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Poster')),
                ('price', models.FloatField(default=0.0, help_text='Enter a value between 0 and 10,000,000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Price')),
                ('discount', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax', models.FloatField(blank=True, default=0.0, help_text='Enter tax amount (0–10,000,000).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Tax')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether the item is active.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='products/gallery/%Y/%d/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Gallery')),
                ('alt_text', models.CharField(blank=True, help_text='Text for SEO and accessibility (alt attribute)', max_length=255, verbose_name='Alt Text')),
                ('is_main', models.BooleanField(default=False, help_text='Check if this is the primary image for the product', verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order of the images', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Uploaded At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.product', verbose_name='Product Gallery')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ('order',),
            },
        ),
    ]
