# Generated by Django 5.2 on 2025-06-05 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=150, unique=True, verbose_name='Username')),
                ('password', models.CharField(help_text='Enter your password', max_length=128, verbose_name='Password')),
                ('email', models.EmailField(help_text='Enter your email', max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(help_text='Author’s name', max_length=150, verbose_name='Name')),
                ('surname', models.CharField(help_text='Enter last name', max_length=150, verbose_name='Surname')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select gender', max_length=1, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, help_text='Enter age in years', null=True, verbose_name='Age')),
                ('bio', models.TextField(blank=True, help_text='Enter a short biography of the author', verbose_name='Biography')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether the item is active.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the brand name.', max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product.', max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.FileField(blank=True, help_text='Upload a category image', null=True, upload_to='category/%Y/%d/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether the item is active.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(help_text='The name of the social network', max_length=150, verbose_name='Social')),
                ('url', models.URLField(help_text='The URL to the social network profile or page', verbose_name='Social Network URL')),
                ('slug', models.SlugField(blank=True, help_text='A slug for the social network', max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Social Logo', null=True, upload_to='social/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Tag name for product', max_length=255, verbose_name='Tag')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-created_at',),
            },
        ),
    ]
