# Generated by Django 5.2 on 2025-06-05 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_author_brand_category_socialnetwork_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the author', null=True, upload_to='authors/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Photo'),
        ),
    ]
