# Generated by Django 5.2 on 2025-04-25 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.FileField(blank=True, help_text='Upload an image', null=True, upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Poster'),
        ),
    ]
