# Generated by Django 5.2 on 2025-06-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_author_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductByPrice',
            fields=[
            ],
            options={
                'ordering': ['-price'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
