# Generated by Django 5.2 on 2025-04-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Author’s name', max_length=150, verbose_name='Name')),
                ('surname', models.CharField(help_text='Enter last name', max_length=150, verbose_name='Surname')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select gender', max_length=1, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Enter age in years', null=True, verbose_name='Age')),
                ('bio', models.TextField(blank=True, help_text='Enter a short biography of the author', verbose_name='Biography')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether the item is active.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the brand name.', max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the product.', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, help_text='Upload the category Image.', null=True, upload_to='category/%Y/%m/%d/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Tag name for product', max_length=255, verbose_name='Tag')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated based on the Name.', max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Indicates whether the item is active.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=2, help_text='Select product author', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.author', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Pick a brand (or skip)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select a Category for the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select a Tag for the product.', related_name='products', to='shop.tag', verbose_name='Tag'),
        ),
    ]
