# Generated by Django 5.2 on 2025-06-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productbyprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Endirimli Mehsullar',
                'verbose_name_plural': 'Endirimli Mehsullar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
