# Generated by Django 5.2 on 2025-06-07 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_salesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=1, help_text='Select product author', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.author', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Pick a brand (or skip)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select product author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='product',
            name='social_network',
            field=models.ForeignKey(help_text='Select a Social media for the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.socialnetwork', verbose_name='Social Media'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select a Tag for the product.', related_name='products', to='shop.tag', verbose_name='Tag'),
        ),
    ]
