# Generated by Django 5.2 on 2025-04-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_author_brand_category_tag_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(help_text='Select product author', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, help_text='Indicates whether the item is active.', verbose_name='Active'),
        ),
    ]
