# Generated by Django 5.2 on 2025-04-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_author_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
