# Generated by Django 5.2 on 2025-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_update_at_author_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
