# Generated by Django 5.2 on 2025-04-27 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_tag_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text='Social Network Logo', null=True, upload_to='social/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, help_text='The name of the social network', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.FileField(blank=True, help_text='Upload an image', null=True, upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5242880)], verbose_name='Poster'),
        ),
    ]
