# Generated by Django 5.2 on 2025-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_logo_product_name_alter_product_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the social network', max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='A slug for the social network', max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Social Network Logo', null=True, upload_to='social/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, help_text='Check this box if the item is active. Uncheck to disable.', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
