# Generated by Django 5.2 on 2025-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_socialnetwork_remove_product_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='name',
            new_name='social',
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='logo',
            field=models.ImageField(blank=True, help_text='Social Logo', null=True, upload_to='social/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
