# Generated by Django 5.2 on 2025-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_name_socialnetwork_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='social',
            field=models.CharField(help_text='The name of the social network', max_length=150, verbose_name='Social'),
        ),
    ]
