# Generated by Django 5.2 on 2025-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_socialnetwork_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(default=1, help_text='The URL to the social network profile or page', verbose_name='Social Network URL'),
            preserve_default=False,
        ),
    ]
