# Generated by Django 5.2 on 2025-05-09 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='Text for SEO and accessibility (alt attribute)', max_length=255, verbose_name='Alt Text')),
                ('is_main', models.BooleanField(default=False, help_text='Check if this is the primary image for the product', verbose_name='Main Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order of the images', verbose_name='Display Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
    ]
