# Generated by Django 5.2 on 2025-05-10 14:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Content about product', verbose_name='Content'),
        ),
    ]
