# Generated by Django 5.2 on 2025-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=2, help_text='Enter your email', max_length=250, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default=1, help_text='Enter your password', max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=1, help_text='Enter username', max_length=150, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
